using FOODGOBACKEND.Dtos.Shipper;
using FOODGOBACKEND.Models;

namespace FOODGOBACKEND.Dtos.Shipper
{
    /// <summary>
    /// DTO for displaying available orders in the free pick screen where shipper can choose orders to deliver.
    /// </summary>
    public class ItemFoodFreePickDto
    {
        /// <summary>
        /// The unique identifier for the order.
        /// Used when shipper clicks "Nhận đơn" button.
        /// </summary>
        public int OrderId { get; set; }

        /// <summary>
        /// URL of the shop/restaurant logo.
        /// Maps to @id/imgShopLogo in the UI.
        /// </summary>
        public string? ShopLogoUrl { get; set; }

        /// <summary>
        /// Name of the shop/restaurant.
        /// Maps to @id/tvShopName in the UI.
        /// </summary>
        public string ShopName { get; set; } = string.Empty;

        /// <summary>
        /// Distance from shipper's current location to the restaurant (calculated by backend).
        /// Example: "Cách bạn 1.3 km"
        /// Maps to @id/tvDistance in the UI.
        /// </summary>
        public string Distance { get; set; } = string.Empty;

        /// <summary>
        /// Main dish summary (first item from OrderItems, auto-generated by backend).
        /// Example: "1x Cơm gà xối mỡ + nước ngọt"
        /// Maps to @id/tvMainDish in the UI.
        /// </summary>
        public string MainDish { get; set; } = string.Empty;

        /// <summary>
        /// Additional items count (auto-generated from OrderItems by backend).
        /// Example: "+ 2 món khác" (will be null or empty if no additional items)
        /// Maps to @id/tvMoreItems in the UI.
        /// </summary>
        public string? MoreItems { get; set; }

        /// <summary>
        /// Delivery destination address (from Orders.DeliveryAddress).
        /// Example: "Giao tới: 45 Nguyễn Trãi, Quận 5"
        /// Maps to @id/tvDestination in the UI.
        /// </summary>
        public string Destination { get; set; } = string.Empty;

        /// <summary>
        /// Total order price (from Orders.TotalAmount).
        /// Example: "Tổng: 125.000đ"
        /// Maps to @id/tvTotalPrice in the UI.
        /// </summary>
        public string TotalPrice { get; set; } = string.Empty;

        /// <summary>
        /// Shipper's income/commission (from Orders.ShippingFee).
        /// Example: "Thu nhập: 27.000đ"
        /// Maps to @id/tvIncome in the UI.
        /// </summary>
        public string Income { get; set; } = string.Empty;
    }
}